//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FatNoder.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_j {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_j() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FatNoder.Properties.Resources.j", typeof(Resources_j).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   条件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConditionNodeViewModel_Compare {
            get {
                return ResourceManager.GetString("ConditionNodeViewModel_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   条件タイプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConditionNodeViewModel_ConditionType {
            get {
                return ResourceManager.GetString("ConditionNodeViewModel_ConditionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   条件 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IfNodeViewModel_ConditionLabel {
            get {
                return ResourceManager.GetString("IfNodeViewModel_ConditionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   でなければ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IfNodeViewModel_ElseLabel {
            get {
                return ResourceManager.GetString("IfNodeViewModel_ElseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   条件分岐 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IfNodeViewModel_IfNodeName {
            get {
                return ResourceManager.GetString("IfNodeViewModel_IfNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~なら に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IfNodeViewModel_ThenLabel {
            get {
                return ResourceManager.GetString("IfNodeViewModel_ThenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mainエントリーポイント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainViewModel_MainEntryPoint {
            get {
                return ResourceManager.GetString("MainViewModel_MainEntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示コンテンツ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintNodeViewModel_PRINTCONTENT {
            get {
                return ResourceManager.GetString("PrintNodeViewModel_PRINTCONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_File_Exit {
            get {
                return ResourceManager.GetString("Ribbon_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   読み込み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_File_Load_As {
            get {
                return ResourceManager.GetString("Ribbon_File_Load_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前を付けて保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_File_Save_As {
            get {
                return ResourceManager.GetString("Ribbon_File_Save_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンパイルして実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_Home_CompileAndRunPhase {
            get {
                return ResourceManager.GetString("Ribbon_Home_CompileAndRunPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動レイアウト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_Layout_Auto_layout {
            get {
                return ResourceManager.GetString("Ribbon_Layout_Auto-layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_Menu_File {
            get {
                return ResourceManager.GetString("Ribbon_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_Menu_Layout {
            get {
                return ResourceManager.GetString("Ribbon_Menu_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_Tab_Home {
            get {
                return ResourceManager.GetString("Ribbon_Tab_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   何算? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueEnzannEngineNodeViewModel_CalcType {
            get {
                return ResourceManager.GetString("ValueEnzannEngineNodeViewModel_CalcType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   足し算 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueEnzannEngineTypeEditorViewModel_ADD {
            get {
                return ResourceManager.GetString("ValueEnzannEngineTypeEditorViewModel_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   割り算 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueEnzannEngineTypeEditorViewModel_Divide {
            get {
                return ResourceManager.GetString("ValueEnzannEngineTypeEditorViewModel_Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   掛け算 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueEnzannEngineTypeEditorViewModel_Multiply {
            get {
                return ResourceManager.GetString("ValueEnzannEngineTypeEditorViewModel_Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   引き算 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueEnzannEngineTypeEditorViewModel_Subtract {
            get {
                return ResourceManager.GetString("ValueEnzannEngineTypeEditorViewModel_Subtract", resourceCulture);
            }
        }
    }
}
