//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FatNoder.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FatNoder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Condition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IfNodeViewModel_ConditionLabel {
            get {
                return ResourceManager.GetString("IfNodeViewModel_ConditionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IfNode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IfNodeViewModel_IfNodeName {
            get {
                return ResourceManager.GetString("IfNodeViewModel_IfNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Then に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IfNodeViewModel_ThenLabel {
            get {
                return ResourceManager.GetString("IfNodeViewModel_ThenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainViewModel_Calc {
            get {
                return ResourceManager.GetString("MainViewModel_Calc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GetValue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainViewModel_GetValue {
            get {
                return ResourceManager.GetString("MainViewModel_GetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main Entry Point に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainViewModel_MainEntryPoint {
            get {
                return ResourceManager.GetString("MainViewModel_MainEntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print String に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainViewModel_PrintString {
            get {
                return ResourceManager.GetString("MainViewModel_PrintString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print content に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PrintNodeViewModel_PRINTCONTENT {
            get {
                return ResourceManager.GetString("PrintNodeViewModel_PRINTCONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_File_Exit {
            get {
                return ResourceManager.GetString("Ribbon_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load As に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_File_Load_As {
            get {
                return ResourceManager.GetString("Ribbon_File_Load_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save As に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_File_Save_As {
            get {
                return ResourceManager.GetString("Ribbon_File_Save_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compile And Run に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_Home_CompileAndRunPhase {
            get {
                return ResourceManager.GetString("Ribbon_Home_CompileAndRunPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_Menu_File {
            get {
                return ResourceManager.GetString("Ribbon_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Layout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_Menu_Layout {
            get {
                return ResourceManager.GetString("Ribbon_Menu_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Home に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Ribbon_Tab_Home {
            get {
                return ResourceManager.GetString("Ribbon_Tab_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap splash {
            get {
                object obj = ResourceManager.GetObject("splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Calc Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueEnzannEngineNodeViewModel_CalcType {
            get {
                return ResourceManager.GetString("ValueEnzannEngineNodeViewModel_CalcType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueEnzannEngineTypeEditorViewModel_ADD {
            get {
                return ResourceManager.GetString("ValueEnzannEngineTypeEditorViewModel_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Divide に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueEnzannEngineTypeEditorViewModel_Divide {
            get {
                return ResourceManager.GetString("ValueEnzannEngineTypeEditorViewModel_Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Multiply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueEnzannEngineTypeEditorViewModel_Multiply {
            get {
                return ResourceManager.GetString("ValueEnzannEngineTypeEditorViewModel_Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subtract に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValueEnzannEngineTypeEditorViewModel_Subtract {
            get {
                return ResourceManager.GetString("ValueEnzannEngineTypeEditorViewModel_Subtract", resourceCulture);
            }
        }
    }
}
