name: build and test

on:
  push:
  pull_request:
    branches: 
      - test
      - master
      - develop

env:
  DOTNET_VERSION: '6.0.202' # The .NET SDK version to use

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies NodeAyanoTest
      run: dotnet restore NodeAyanoTest

    - name: Install dependencies AyanoPluginCommonAPI.Tests
      run: dotnet restore AyanoPluginCommonAPI.Tests
      
    - name: Build NodeAyanoTest
      run: dotnet build --configuration Release --no-restore NodeAyanoTest

    - name: Build AyanoPluginCommonAPI.Tests
      run: dotnet build --configuration Release --no-restore AyanoPluginCommonAPI.Tests
    
    - name: Test NodeAyanoTest
      run: dotnet test --no-restore --verbosity normal NodeAyanoTest

    - name: Test AyanoPluginCommonAPI.Tests
      run: dotnet test --no-restore --verbosity normal AyanoPluginCommonAPI.Tests
